### ISSUE TITLE
 Unexpected Exception, this is probably a bug: cannot import name '_psutil_linux' 

### ISSUE THREAD

**Issue by needle2k** [ManageIQ/ansible-manageiq-automate#17]
Hi, 

if i´m using the role manageiq.manageiq_automate i receive this Error by using Ansible Playbook Method

i got 2 Appliances 

1x ManageIQ Version:        najdorf-1.3
1x ManageIQ Version:        oparin-1.1

and both having the same issue

/var/www/miq/vmdb/log]# tail -f evm.log | grep ERROR

```bash
{"event"=>"verbose", "uuid"=>"6364e89c-f42e-4ba0-8fbb-19112b50597c", "counter"=>15, "stdout"=>"ERROR! Unexpected Exception, this is probably a bug: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib64/python3.6/site-packages/psutil/init.py)", "start_line"=>14, "end_line"=>15, "runner_ident"=>"result"}
[----] E, [2023-03-16T11:28:12.829545 #2304:bb698] ERROR -- evm: MIQ(MiqAeEngine.deliver) Error delivering {"dialog_param_input_hostname"=>"", "dialog_param_input_fqdn"=>"", "dialog_param_input_sockets"=>"1", "dialog_text_box_3"=>"4", "dialog_text_box_1"=>"16 GB", "dialog_param_input_lvs_dropdown"=>nil, "dialog_text_box_2"=>"", "dialog_text_box_4"=>"", "dialog_radio_button_1"=>"1", "dialog_text_box_5"=>"", "User::user"=>1, "ServiceTemplate::service_template"=>17} for object [ServiceTemplate.17] with state [] to Automate: ansible playbook failed
[----] E, [2023-03-16T11:28:12.831150 #2304:bb698] ERROR -- evm: [NoMethodError]: undefined method root' for nil:NilClass  Method:[rescue in values_from_automate] [----] E, [2023-03-16T11:28:12.831594 #2304:bb698] ERROR -- evm: /var/www/miq/vmdb/app/models/dynamic_dialog_field_value_processor.rb:14:in values_from_automate'
```

My Ansible Playbook is very simple and added via scm

> roles
   > manageiq.manageiq_atomate
testplaybook.yaml 

```yaml
- name: Embedded Ansible | Test | Start
  hosts: localhost
  connection: local
  vars:
    - auto_commit: True
    - object: root
    - interval: 600
  gather_facts: False

  roles:
  - manageiq.manageiq_automate

  roles:
  - manageiq.manageiq_automate

  - name: Get the full list of objects/instances in the workspace (get_object_names)
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_object_names: yes
    register: workspace_object_names

  - name: DEBUG object_names
    debug: 
      msg: "{{ workspace_object_names }}"
```

thx
